name: Maven Central publishing

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: "Importing GPG key"
        run: |
          sudo gpg --batch --passphrase ${{ secrets.GPG_PASSPHRASE }} --import gradle/secring.gpg

      - name: "Installing CUDA Toolkit"
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-6
          
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/cross-linux-aarch64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-cross-aarch64

      - name: "Prepare"
        run: |
          chmod +x ./gradlew

      - name: "Building and publishing"
        run: >
          ./gradlew publish
          -Dorg.gradle.project.signing.password=${{ secrets.GPG_PASSPHRASE }}
          -Dorg.gradle.project.signing.secretKeyRingFile=${{ github.workspace }}/gradle/secring.gpg
          -Dorg.gradle.project.ossrhUsername=${{ secrets.SONATYPE_USERNAME }}
          -Dorg.gradle.project.ossrhPassword=${{ secrets.SONATYPE_PASSWORD }}